spring:
  application:
    name: spring3-cassandra

# ===============================
# = DATABASE CASSANDRA
# ===============================
  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:localhost}
    port: ${SPRING_CASSANDRA_PORT:9042}
    local-datacenter: datacenter1
    keyspace-name: mykeyspace   # optional

# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

# ===============================
# = OPENZIPKIN
# ===============================
  tracing:
    enabled: true
    sampling:
      probability: 0.2   # 20% das requisições são amostradas
  zipkin:
    tracing:
      endpoint: ${URL_OPENZIPKIN:http://192.168.0.100:9411/api/v2/spans}

  logging:
    pattern:
      correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
    include-application-name: false

# ===============================
# Clients externos (e.g., API de teste)
# ===============================
apps:
  api-teste:
    url: ${URL_API_TESTE:http://localhost:8383}
  gateway:
    url: ${URL_GATEWAY:http://localhost:8080}

# ===============================
# = SERVICE
# ===============================
server:
  port: 8089
