spring:
  application:
    name: spring3-cassandra

  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:cassandralocal}
    port: ${SPRING_CASSANDRA_PORT:9042}
    local-datacenter: datacenter1
#    keyspace-name: mykeyspace   # optional

# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

  # ===============================
  # = OPENZIPKIN
  # ===============================
#  tracing:
#    sampling:
#      probability: 0.2   # 20% das requisições; em produção use valores menores
#    export:
#      zipkin:
#        endpoint: ${URL_OPENZIPKIN:http://192.168.0.100:9411/api/v2/spans}

  tracing:
    enabled: true
    sampling:
      probability: 0.2   # 20% das requisições são amostradas
  zipkin:
    tracing:
      endpoint: ${URL_OPENZIPKIN:http://192.168.0.100:9411/api/v2/spans}
